//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchooT.UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tBatch()
        {
            this.tBatchClassSections = new HashSet<tBatchClassSection>();
            this.tPeriods = new HashSet<tPeriod>();
        }
    
        public int bat_id { get; set; }
        public string bat_Name { get; set; }
        public string bat_DisplayName { get; set; }
        public Nullable<bool> bat_IsDeleted { get; set; }
        public Nullable<System.DateTime> bat_DeletedDate { get; set; }
        public Nullable<int> bat_DeletedBy { get; set; }
        public Nullable<int> bat_CreatedBy { get; set; }
        public Nullable<System.DateTime> bat_CreatedDate { get; set; }
        public Nullable<System.DateTime> bat_LastUpdatedDate { get; set; }
        public Nullable<int> bat_LastUpdateBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBatchClassSection> tBatchClassSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPeriod> tPeriods { get; set; }
    }
}
