//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchooT.UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tClass()
        {
            this.tBatchClassSections = new HashSet<tBatchClassSection>();
            this.tClassSubjects = new HashSet<tClassSubject>();
            this.tPeriods = new HashSet<tPeriod>();
        }
    
        public int cla_id { get; set; }
        public string cla_Name { get; set; }
        public Nullable<int> cla_CreatedBy { get; set; }
        public Nullable<int> cla_UpdatedBy { get; set; }
        public Nullable<System.DateTime> cla_CreationDate { get; set; }
        public Nullable<System.DateTime> cla_UpdatedDate { get; set; }
        public Nullable<bool> cla_IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBatchClassSection> tBatchClassSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tClassSubject> tClassSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPeriod> tPeriods { get; set; }
    }
}
