//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchooT.UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHoliday
    {
        public int hod_Id { get; set; }
        public string hod_Name { get; set; }
        public Nullable<int> hod_TypeId { get; set; }
        public Nullable<System.DateTime> hod_From { get; set; }
        public Nullable<System.DateTime> hod_To { get; set; }
        public Nullable<int> hod_CreatedBy { get; set; }
        public Nullable<int> hod_UpdatedBy { get; set; }
        public Nullable<System.DateTime> hod_CreatedDate { get; set; }
        public Nullable<System.DateTime> hod_UpdatedDate { get; set; }
        public Nullable<bool> hod_IsDeleted { get; set; }
    
        public virtual tHolidayType tHolidayType { get; set; }
    }
}
