//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchooT.UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHolidayType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tHolidayType()
        {
            this.tHolidays = new HashSet<tHoliday>();
        }
    
        public int hot_Id { get; set; }
        public string hot_Name { get; set; }
        public Nullable<int> hot_CreatedBy { get; set; }
        public Nullable<int> hot_UpdatedBy { get; set; }
        public Nullable<System.DateTime> hot_CreatedDate { get; set; }
        public Nullable<System.DateTime> hot_UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tHoliday> tHolidays { get; set; }
    }
}
