//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchooT.UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPeriod()
        {
            this.tTimeTables = new HashSet<tTimeTable>();
        }
    
        public int per_Id { get; set; }
        public Nullable<System.TimeSpan> per_StartTime { get; set; }
        public Nullable<System.TimeSpan> per_EndTime { get; set; }
        public string per_Name { get; set; }
        public Nullable<int> per_Length { get; set; }
        public Nullable<int> per_ClassId { get; set; }
        public Nullable<int> per_BatchId { get; set; }
        public Nullable<int> per_CreatedBy { get; set; }
        public Nullable<int> per_UpdatedBy { get; set; }
        public Nullable<System.DateTime> per_CreatedDate { get; set; }
        public Nullable<System.DateTime> per_UpdatedDate { get; set; }
        public Nullable<bool> per_IsDeleted { get; set; }
        public Nullable<System.DateTime> per_DeletedDate { get; set; }
        public Nullable<int> per_DeletedBy { get; set; }
        public bool per_IsBreak { get; set; }
    
        public virtual tBatch tBatch { get; set; }
        public virtual tClass tClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTimeTable> tTimeTables { get; set; }
    }
}
