//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchooT.UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSection()
        {
            this.tBatchClassSections = new HashSet<tBatchClassSection>();
        }
    
        public int sec_id { get; set; }
        public string sec_SectionName { get; set; }
        public string sec_DisplayName { get; set; }
        public Nullable<bool> sec_IsDeleted { get; set; }
        public Nullable<System.DateTime> sec_CreatedDate { get; set; }
        public Nullable<int> sec_CreatedBy { get; set; }
        public Nullable<int> sec_LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> sec_LastUpdatedDate { get; set; }
        public Nullable<System.DateTime> sec_DeletedDate { get; set; }
        public Nullable<int> sec_DeletedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBatchClassSection> tBatchClassSections { get; set; }
    }
}
