//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchooT.UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStaffSubject
    {
        public int stcg_Id { get; set; }
        public Nullable<int> stcg_StaffId { get; set; }
        public Nullable<int> stcg_SubjectId { get; set; }
        public Nullable<int> stcg_CreatedBy { get; set; }
        public Nullable<int> stcg_UpdatedBy { get; set; }
        public Nullable<System.DateTime> stcg_CreatedDate { get; set; }
        public Nullable<System.DateTime> stcg_UpdatedDate { get; set; }
        public Nullable<bool> stcg_IsDeleted { get; set; }
    
        public virtual tStaff tStaff { get; set; }
        public virtual tSubject tSubject { get; set; }
    }
}
