//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchooT.UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSubject()
        {
            this.tClassSubjects = new HashSet<tClassSubject>();
            this.tStaffSubjects = new HashSet<tStaffSubject>();
            this.tTimeTables = new HashSet<tTimeTable>();
        }
    
        public int sub_Id { get; set; }
        public string sub_Name { get; set; }
        public Nullable<bool> sub_IsHeavy { get; set; }
        public Nullable<int> sub_Priority { get; set; }
        public Nullable<bool> sub_IsDouble { get; set; }
        public Nullable<int> sub_CreatedBy { get; set; }
        public Nullable<int> sub_UpdatedBy { get; set; }
        public Nullable<System.DateTime> sub_CreationDate { get; set; }
        public Nullable<System.DateTime> sub_UpdatedDate { get; set; }
        public Nullable<bool> sub_IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tClassSubject> tClassSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tStaffSubject> tStaffSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTimeTable> tTimeTables { get; set; }
    }
}
