//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchooT.UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTimeTableConstraintType
    {
        public int tct_Id { get; set; }
        public string tct_Name { get; set; }
        public Nullable<int> tct_CreatedBy { get; set; }
        public Nullable<int> tct_UpdatedBy { get; set; }
        public Nullable<System.DateTime> tct_CreatedDate { get; set; }
        public Nullable<System.DateTime> ct_UpdatedDate { get; set; }
    }
}
