//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchooT.UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTimeTable
    {
        public int tit_id { get; set; }
        public Nullable<int> tit_BatchClassSectionId { get; set; }
        public Nullable<int> tit_StaffId { get; set; }
        public Nullable<int> tit_WeekDay { get; set; }
        public Nullable<int> tit_PeriodId { get; set; }
        public Nullable<int> tit_SubjectId { get; set; }
        public Nullable<int> tit_CreatedBy { get; set; }
        public Nullable<int> tit_UpdatedBy { get; set; }
        public Nullable<System.DateTime> tit_CreatedDate { get; set; }
        public Nullable<System.DateTime> tit_UpdatedDate { get; set; }
        public Nullable<bool> tit_IsDeleted { get; set; }
    
        public virtual tBatchClassSection tBatchClassSection { get; set; }
        public virtual tPeriod tPeriod { get; set; }
        public virtual tStaff tStaff { get; set; }
        public virtual tSubject tSubject { get; set; }
    }
}
